feat(ds): session expiry
emqx/emqx pull request #12024
Opened 2023-11-24 17:53 UTC by thalesmg

Fixes https://emqx.atlassian.net/browse/EMQX-11048

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

2023-11-24 19:45 UTC, ieQu1 submitted a review, later dismissed

2023-11-24 20:53 UTC, ieQu1 commented on apps/emqx/src/emqx_persistent_session_ds.erl
> +                        %% Should we drop the session now, or leave it to session GC?
Should we drop the old mnesia data as well? Otherwise it'll leave streams and subscriptions linger

2023-11-26 15:58 UTC, ieQu1 requested changes
We must avoid de-syncing RAM-state with mnesia state.

Currently the following problem will likely happen:
- Client connects and subscribes to topics
- Disconnects, expiry interval passes
- Re-connects, this code will pretend that the session was clean; but the old subscriptions/ranges are still in the tables
- Disconnects, with updated expire date
- Reconnects within expiry interval. Suddenly the subscriptions made at the very first step reappear.

2023-11-26 18:20 UTC, ieQu1 commented
I added a few changes during local testing: https://github.com/ieQu1/emqx/tree/dev/ds-session-cleanup

2023-11-27 17:03 UTC, ieQu1 approved these changes

2023-11-27 17:11 UTC, merged

2023-11-28 12:54 UTC, thalesmg commented on apps/emqx/src/emqx_persistent_session_ds.erl
> +    NowMS = now_ms(),
Good point, I'll adjust this.