fix(banned): treat fuzzy search input as a literal string
emqx/emqx pull request #13885
Opened 2024-09-27 08:46 UTC by lafirest

Fixes EMQX-13181

Release version: v/e5.?

## Summary

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Added property-based tests for code which performs user input validation
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/(ce|ee)/(feat|perf|fix|breaking)-<PR-id>.en.md` files
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] Created PR to [emqx-docs](https://github.com/emqx/emqx-docs) if documentation update is required, or link to a follow-up jira ticket
- [ ] Schema changes are backward compatible

## Checklist for CI (.github/workflows) changes

- [ ] If changed package build workflow, pass [this action](https://github.com/emqx/emqx/actions/workflows/build_packages.yaml) (manual trigger)
- [ ] Change log has been added to `changes/` dir for user-facing artifacts update

2024-09-28 05:46 UTC, zmstone requested changes
Explain this to me: how can we escape a regexp pattern and still expect it to work as regexp pattern ?

This is the minimal example to reproduce the issue provided in jira:
```
> re:run(<<"a">>, <<"[]">>).
** exception error: bad argument
     in function  re:run/2
        called as re:run(<<"a">>,<<"[]">>)
        *** argument 2: could not parse regular expression
                        missing terminating ] for character class on character 3
```
IMO, it should not be escaped, but rather just fail with a more meaningful error message.

2024-09-28 05:48 UTC, zmstone commented
this can be useful to generate a meaningful error message:
```
> re:compile(<<"[]">>).
{error,{"missing terminating ] for character class",2}}
```

2024-09-29 02:11 UTC, lafirest commented
> Explain this to me: how can we escape a regexp pattern and still expect it to work as regexp pattern ?
> 
> This is the minimal example to reproduce the issue provided in jira:
> 
> ```
> > re:run(<<"a">>, <<"[]">>).
> ** exception error: bad argument
>      in function  re:run/2
>         called as re:run(<<"a">>,<<"[]">>)
>         *** argument 2: could not parse regular expression
>                         missing terminating ] for character class on character 3
> ```
> 
> IMO, it should not be escaped, but rather just fail with a more meaningful error message.

Yes, this was a wrong fix, I forgot to switch it to draft.

2024-09-30 06:33 UTC, zmstone reviewed
Add a test to cover `400` ?

2024-09-30 07:45 UTC, zmstone commented on rel/i18n/emqx_mgmt_api_banned.hocon
> +"""Fuzzy query banned objects with a regex expression for CIDR."""
Question: does it make sense to use regex match against a CIDR?

CIDR is already kind of a 'fuzzy' (or 'range' query).

2024-09-30 07:47 UTC, zmstone commented on rel/i18n/emqx_mgmt_api_banned.hocon
> +"""Fuzzy query banned objects with a regex expression for IP address."""
need a test case for this one.
because ip internally could be a tuple instead of a string,
use re:run against a tuple will crash.

2024-10-08 08:56 UTC, lafirest commented on rel/i18n/emqx_mgmt_api_banned.hocon
> +"""Fuzzy query banned objects with a regex expression for IP address."""
It is already covered by the previous PR, the tuple will be converted to string first.

2024-10-08 08:57 UTC, lafirest commented on rel/i18n/emqx_mgmt_api_banned.hocon
> +"""Fuzzy query banned objects with a regex expression for CIDR."""
CIDRs are treated as strings and users can search for them using parts of the string or regular expressions.

2024-10-08 10:48 UTC, zmstone approved these changes

2024-10-08 11:39 UTC, merged

2024-10-10 11:07 UTC, emqxqa commented
[TestExecution](https://emqx.atlassian.net/browse/QA-4408)