Chore/merge enterprise mangement
emqx/emqx pull request #4241
Opened 2021-02-25 09:56 UTC by Rory-Z

Fixes <issue-number>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/emqx/emqx/blob/master/CONTRIBUTING.md.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## Backward Compatibility

## More information

2021-02-25 10:43 UTC, HJianBo requested changes

2021-02-25 10:43 UTC, HJianBo commented on apps/emqx_management/src/emqx_mgmt_api_pubsub.erl
> +            case get_value(<<"return">>, Params, undefined) of
Need to update docs

2021-02-25 10:43 UTC, HJianBo commented on apps/emqx_management/src/emqx_mgmt_cli.erl
> +            emqx_ctl:print("The emqx data import failed. ~n");
Delete needless space

2021-02-26 01:16 UTC, turtleDeng commented on apps/emqx_management/src/emqx_mgmt_data_backup.erl
> +    do_import_extra_data(Data, Version).
do_import_extra_data Need first call

2021-02-26 01:16 UTC, turtleDeng commented on apps/emqx_management/src/emqx_mgmt_data_backup.erl
> +    import_resources(maps:get(<<"resources">>, Data, [])),
import_resources_and_rules(maps:get(<<"resources">>, Data, []), maps:get(<<"rules">>, Data, []), Version).

2021-03-01 05:54 UTC, turtleDeng submitted a review, later dismissed

2021-03-01 05:57 UTC, HJianBo submitted a review, later dismissed

2021-03-01 09:11 UTC, tigercl commented on apps/emqx_management/src/emqx_mgmt_data_backup.erl
> +                                            FromVersion =:= "4.1" ->
Add FromVersion =:=  "4.2" case

2021-03-01 09:12 UTC, tigercl commented on apps/emqx_management/src/emqx_mgmt_data_backup.erl
> +import_acl_mnesia(Acls, FromVersion) when FromVersion =:= "4.0" orelse
Add FromVersion =:= "4.2" case

2021-03-01 09:33 UTC, tigercl submitted a review, later dismissed

2021-03-02 00:46 UTC, turtleDeng approved these changes

2021-03-02 01:35 UTC, merged