feat(rule-engine): list rule support order by timestrap
emqx/emqx pull request #4298
Opened 2021-03-06 07:51 UTC by wwhai

Fixes <issue-number>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/emqx/emqx/blob/master/CONTRIBUTING.md.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## Backward Compatibility

## More information

2021-03-09 03:21 UTC, terry-xiaoyu requested changes

2021-03-09 03:21 UTC, terry-xiaoyu commented on apps/emqx_rule_engine/src/emqx_rule_engine_api.erl
> +    parse_rule_params(Params, Rule#{created_at => erlang:system_time(millisecond)}).
create_at should be calculated in the emqx_rule_engine:create_rule/1.

2021-03-09 03:21 UTC, terry-xiaoyu commented on apps/emqx_rule_engine/src/emqx_rule_registry.erl
> +get_rules_order_by_ts() ->
get_rules_ordered_by_ts

2021-03-09 03:21 UTC, terry-xiaoyu commented on apps/emqx_rule_engine/src/emqx_rule_registry.erl
> +get_rules_order_by_ts() ->
The function get_rules_ordered_by_ts/0 should be used both by API and CLI, and the test case for the API and CLI should be updated to verify the ordering.

2021-03-12 06:39 UTC, terry-xiaoyu approved these changes

2021-03-12 06:39 UTC, terry-xiaoyu commented on apps/emqx_rule_engine/src/emqx_rule_registry.erl
> +    List.
We need to add a test case for this function.

2021-03-12 08:21 UTC, terry-xiaoyu approved these changes

2021-03-12 09:04 UTC, HJianBo approved these changes

2021-03-12 09:07 UTC, HJianBo commented
Does CLI need to return an ordered rules?

2021-03-12 09:35 UTC, merged