feat(mgmt): add restart support
emqx/emqx pull request #4301
Opened 2021-03-08 06:17 UTC by wwhai

Fixes <issue-number>

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/emqx/emqx/blob/master/CONTRIBUTING.md.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## Backward Compatibility

## More information

2021-03-08 14:17 UTC, zmstone requested changes

2021-03-08 14:17 UTC, zmstone commented on apps/emqx_management/src/emqx_mgmt_cli.erl
> +        case Identifier = atom_to_list(Protocol) ++ ":dashboard" of
this  variable `Identifier` is clashing with the one at line 688.

2021-03-08 14:17 UTC, zmstone commented on apps/emqx_management/src/emqx_mgmt_cli.erl
> +        case Identifier = atom_to_list(Protocol) ++ ":dashboard" of
```
case Protocol =:= atom_to_list(Protocol) ++ ":dashboard" of
    true ->
        restart(emqx_dashboard, Protocol, Port, Options);
    false ->
        ok
end
```

2021-03-09 07:55 UTC, terry-xiaoyu requested changes

2021-03-09 07:55 UTC, terry-xiaoyu commented on apps/emqx_management/src/emqx_mgmt_cli.erl
> +    lists:foreach(fun({Protocol ,Port, Options}) ->
Reformat the comma and spaces:

```suggestion
    lists:foreach(fun({Protocol, Port, Options}) ->
```

2021-03-09 07:55 UTC, terry-xiaoyu commented on apps/emqx_management/src/emqx_mgmt_cli.erl
> +restart_emqx_management(Identifier) ->
I noticed that restart_emqx_management/1 and restart_emqx_dashboard/1 are almost in the same structure. Then rewrite it into a common function would make sense.

2021-03-10 03:59 UTC, terry-xiaoyu requested changes

2021-03-10 03:59 UTC, terry-xiaoyu commented on apps/emqx_management/src/emqx_mgmt_cli.erl
> +
```suggestion
listeners(["restart", "http:dashboard" = Identifier]) ->
    restart_http_listener(http, emqx_dashboard);
listeners(["restart", "https:dashboard" = Identifier]) ->
    restart_http_listener(https, emqx_dashboard);
   
```

2021-03-10 12:07 UTC, zmstone commented
commit log looks unrelated.
e.g.
feat(rule-engine): reformat code style

2021-03-10 16:27 UTC, zmstone approved these changes

2021-03-10 16:29 UTC, merged