feat(emqx_ws_connection): #4184 check http header to know real IP/port
emqx/emqx pull request #4558
Opened 2021-04-13 11:15 UTC by z8674558

Fixes #4184

**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: https://github.com/emqx/emqx/blob/master/CONTRIBUTING.md.

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## Backward Compatibility

## More information

2021-04-13 17:37 UTC, zmstone requested changes

2021-04-13 17:37 UTC, zmstone commented on priv/emqx.schema
> +  {datatype, {enum, [x_forwarded_for]}}
should be a string type,
as a user, I would not like to edit schema if I want to use a different header name.

2021-04-13 17:37 UTC, zmstone commented on priv/emqx.schema
> +  {datatype, {enum, [x_forwarded_for]}}
Add default value "X-Forwarded-For"

2021-04-13 17:37 UTC, zmstone commented on etc/emqx.conf
> +## Value: Enum
should be a string type.

2021-04-13 17:37 UTC, zmstone commented on etc/emqx.conf
> +## Use X-Forwarded-For header for real source IP if the EMQ X cluster is
```suggestion
## Specify which HTTP header for real source IP if the EMQ X cluster is
```

2021-04-13 17:37 UTC, zmstone commented on src/emqx_ws_connection.erl
> +                        Addr = case proplists:get_value(proxy_address_header, Opts) of
break this out to a small function ?

2021-04-13 17:37 UTC, zmstone commented on src/emqx_ws_connection.erl
> +                            x_forwarded_for ->
should get back a string, `HeaderName` then call 
`cowboy_req:header(lowercase(HeaderName), Req, <<>>)`

2021-04-13 17:37 UTC, zmstone commented on src/emqx_ws_connection.erl
> +                            _ ->
if the schema is created with a default value, this clause is not necessary.

2021-04-14 02:36 UTC, HJianBo commented on priv/emqx.schema
> +  {default, "X-Forwarded-For"},
The default value here means that the behavior of parsing `X-Forward-*` is turned on by default, is this purposely done here?

My opinion is that, first of all, this is different from the previous design (in 2.3.11). The previous logic required the configuration to be manually enabled to allow parsing of `X-Forward-*`; when the configuration was commented out, it meant that `X-Forward-*` would not be parsed.

2021-04-14 02:38 UTC, HJianBo commented on priv/emqx.schema
> +  {default, "X-Forwarded-For"},
By default we should turn this off, is this ok? 

Or at least it should allow the user a way to turn it off.

2021-04-14 04:38 UTC, zmstone commented
@HJianBo I don’t think it’s necessary to turn it off by default.
Showing haproxy ip as client ip by default is a bug .
And http layer headers should override tcp layer’s binary PROXY protocol ( maybe turn on binary protocol flag by default too)

X-Forwarded-For is almost the standard, see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For

2021-04-14 05:27 UTC, HJianBo approved these changes

2021-04-14 06:45 UTC, zmstone approved these changes

2021-04-14 06:45 UTC, merged