Expose Internal MQTT Service
emqx/emqx pull request #5457
Opened 2021-08-11 14:15 UTC by 1995parham

Having an internal MQTT service on a pod doesn't have many use cases but by exposing it on a cluster we can connect our internal services to the MQTT without ACL or authentication. In this PR users can enable this service by setting the following variable:

```
EMQX_LISTENER__TCP__INTERNAL: 11883
```

just like the other environment variables.

2021-08-11 18:18 UTC, 1995parham commented
Because it is related to v4.3, it should be on its branch or there is no problem for this PR being on master?

2021-08-11 21:17 UTC, k32 commented
Hello,

I believe you'll need to backport the fix to `main-v4.3` branch, after this PR is merged. However, I am not very familiar with the process related to the helm chart.

2021-08-12 03:32 UTC, Rory-Z requested changes

2021-08-12 03:32 UTC, Rory-Z commented on deploy/charts/emqx/templates/StatefulSet.yaml
> +          - name: internalmqtt
It looks like line 124 should be `- name: internalmqtt` and line 128 should be `- name: dashboardtls`

2021-08-12 03:32 UTC, Rory-Z commented on deploy/charts/emqx/templates/service.yaml
> +  - name: mqtt
Maybe this name should be `internalmqtt `

2021-08-12 06:23 UTC, Rory-Z commented
Thanks for your contribution, I will merge this PR, can you please create a new PR to merge this change into the master branch?

2021-08-12 06:23 UTC, Rory-Z approved these changes

2021-08-12 06:24 UTC, merged

2021-08-12 06:43 UTC, 1995parham commented
@Rory-Z Sure, I will create a new PR on master.

2021-08-12 06:44 UTC, Rory-Z commented
> @Rory-Z Sure, I will create a new PR on master.

Thx ：）