feat(psk): support psk
emqx/emqx pull request #5773
Opened 2021-09-18 08:59 UTC by tigercl

2021-09-18 09:06 UTC, zmstone commented on apps/emqx_psk/etc/emqx_psk.conf
> +    # boot_file = {{ platform_data_dir }}/boot.psk
init_file maybe

2021-09-26 01:20 UTC, terry-xiaoyu commented on apps/emqx_psk/data/init.psk
> +myclient1:8c701116e9127c57a99d5563709af3deaca75563e2c4dd0865701ae839fb6d79
Suggest to change the filename to `psk.txt`

2021-09-26 01:20 UTC, terry-xiaoyu commented on apps/emqx_psk/data/init.psk
> +myclient1:8c701116e9127c57a99d5563709af3deaca75563e2c4dd0865701ae839fb6d79
Or just `psk` or `psk_file`?

2021-09-26 01:31 UTC, terry-xiaoyu commented
Another problem is, the psk file is loaded to a replicated mnesia table, but if the psk files on different nodes are not identical, then it is hard to know which one is used by the system.

2021-09-26 01:38 UTC, terry-xiaoyu commented
A better solution is to use the psk file like a configuration file, so the user is sure that the current node always maintains the same psk-list in the memory and the file), do not provide APIs for adding/removing a single PSK-ID/PSK pair. It is the user's responsibility to keep the files identical on different nodes.

2021-09-26 07:32 UTC, terry-xiaoyu approved these changes

2021-09-26 12:47 UTC, zmstone commented
Add test cases.

2021-09-26 12:47 UTC, zmstone requested changes

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +            _ = file:close(Io),
close in the `after` clause of a `try. ... after`

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +    gen_server:call(?MODULE, {import, SrcFile}).
infinity timeout.

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +                    ?LOG(warning, "Failed to import psk from ~s due to ~p", [SrcFile, Reason])
```suggestion
                    ?SLOG(error, #{msg => "failed_to_miport_psk_file",  file => SrcFile, reason => Reason})
```

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +                ok -> ignore;
```suggestion
                ok -> ok;
```

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +            false -> ok
```suggestion
            false ->
                ?SLOG(info, #{msg =>"emqx_psk_disabled"})
```

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +    ?LOG(error, "Unexpected call: ~p", [Req]),
```suggestion
    ?LOG(info, #{msg => "unexpected_call_discarded", call => Req}),
```

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +    {reply, ignored, State}.
```suggestion
    {reply, {error, unexpected}, State}.
```

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +    ?LOG(error, "Unexpected case: ~p", [Req]),
```suggestion
    ?SLOG(info, #{msg => "unexpected_cast_discarded", cast => Req}),
```

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +    ?LOG(error, "Unexpected info: ~p", [Info]),
```suggestion
    ?SLOG(info, #{msg => "unexpected_info_discarded", info => Info}),
```

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +    case get_psks(Io, Delimiter, 50) of
make the chunk size `50` configurable

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +                    shared_secret :: binary()}).
```suggestion
                    shared_secret :: binary()
                    extra :: term()
                    }).
```

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +                    shared_secret :: binary()}).
this is to get ready for future extension without having to change mnesia schema.

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk_schema.erl
> +enable(type) -> boolean();
add `desc` clause

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk_schema.erl
> +init_file(type) -> binary();
add `desc` clause

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk_schema.erl
> +separator(type) -> binary();
add `desc` clause.

2021-09-26 12:47 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +                {rlog_shard, ?PSK_SHARD},
add
 `{type, ordered_set}`

this will make future pagination easier.

2021-09-27 01:56 UTC, tigercl commented on apps/emqx_psk/src/emqx_psk.app.src
> +  {vsn, "5.0.0"}, % strict semver, bump manually!
All other apps are 5.0.0 now.

2021-09-27 03:51 UTC, zmstone commented on apps/emqx/src/emqx_tls_psk.erl
> -            ?LOG(error, "Look PSK for PSKID ~p error: ~p", [ClientPSKID, Error]),
SLOG

2021-09-27 03:52 UTC, zmstone commented on apps/emqx_psk/etc/emqx_psk.conf
> +    ## The size of each chunk used to import to the built-in database from psk file
Also applies to future HTTP API

2021-09-27 03:56 UTC, zmstone requested changes
Add test cases

2021-09-27 08:12 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +                    {error, {bad_format, Line}}
this will potentially cause secrets getting logged.
report just line number

2021-09-27 08:13 UTC, zmstone requested changes

2021-09-27 08:13 UTC, zmstone commented on apps/emqx_psk/src/emqx_psk.erl
> +                                   class => Class,
```suggestion
                                   exception => Class,
```

2021-09-28 07:25 UTC, zmstone approved these changes

2021-09-29 05:37 UTC, merged