fix(ssl): fix the issue that the content of TLS certificate is not converted to path
emqx/emqx pull request #6059
Opened 2021-11-04 05:33 UTC by tigercl

2021-11-11 21:39 UTC, zmstone commented
Test cases are failing.

2021-11-11 22:20 UTC, zmstone requested changes

2021-11-11 22:20 UTC, zmstone commented on apps/emqx_authn/src/emqx_authn_api.erl
> +convert_certs(#{ssl := SSLOpts} = Config) ->
doesn't this function work on the raw config?

2021-11-11 22:20 UTC, zmstone commented on apps/emqx_authn/src/emqx_authn_api.erl
>                                         Acc#{K => Bin}
If the intension is to *NOT* return file content in the HTTP response, shouldn't we just skip doing this?

2021-11-22 22:31 UTC, zmstone commented on apps/emqx_authn/src/emqx_authn_api.erl
> +convert_certs(#{ssl := SSLOpts} = Config) ->
for the record: it is indeed raw config as input, but filled with defaults, and checked with `atom_keys` option

2021-11-23 02:37 UTC, terry-xiaoyu approved these changes

2021-11-23 02:38 UTC, merged