feat(exhook): expose headers for on_messages_publish hook
emqx/emqx pull request #6076
Opened 2021-11-05 10:33 UTC by HJianBo

2021-11-09 08:07 UTC, zmstone commented on apps/emqx_exhook/src/emqx_exhook_server.erl
> +                       catch T:R:_ -> {T,R}
```suggestion
                       catch T:R -> {T,R}
```

2021-11-11 11:37 UTC, tigercl commented on apps/emqx_coap/src/emqx_coap.app.src
> +  {vsn, "4.3.1"}, % strict semver, bump manually!
4.4.0？

2021-11-11 22:39 UTC, zmstone requested changes

2021-11-11 22:39 UTC, zmstone commented on apps/emqx_lwm2m/src/emqx_lwm2m.app.src
> +              {vsn, "4.3.5"}, % strict semver, bump manually!
maybe bump to 4.4.0

2021-11-11 22:39 UTC, zmstone commented on apps/emqx_stomp/src/emqx_stomp.app.src
> +  {vsn, "4.3.3"}, % strict semver, bump manually!
4.4.0

2021-11-12 01:54 UTC, HJianBo commented on apps/emqx_coap/src/emqx_coap.app.src
> +  {vsn, "4.3.1"}, % strict semver, bump manually!
It's not a feature, it's more like a bugfix or enhancement. I'll sync the changes to this application to the main-4.3 branch later.

2021-11-12 02:56 UTC, HJianBo commented
Some commits have a port to main-v4.3
https://github.com/emqx/emqx/pull/6139

2021-11-15 02:05 UTC, terry-xiaoyu approved these changes

2021-11-15 02:23 UTC, merged