chore: refactor ?SLOG
emqx/emqx pull request #6478
Opened 2021-12-17 16:20 UTC by Spycsh

2021-12-17 17:05 UTC, zmstone requested changes

2021-12-17 17:05 UTC, zmstone commented on apps/emqx_retainer/src/emqx_retainer_mnesia.erl
> +                                  ?SLOG(error,
We should not write logs in mnesia transaction!
abort the transaction here with
`mnesia:abort(table_is_full)`
and later:

```
case mria:transaction(?RETAINER_SHARD, Fun) of
    {atomic, ok} ->  ok;
    {aborted, Reason} -> ?SLOG(error, #{msg => "failed_to_retain_message", topic => Topic, reason => Reason})
end
```

2021-12-17 17:05 UTC, zmstone commented on apps/emqx_retainer/src/emqx_retainer_pool.erl
> +            ?SLOG(error, #{msg => "aync_submit_error", error => Error, stacktrace => Stacktrace})
```suggestion
            ?SLOG(error, #{msg => "crashed_handling_async_task", exception => Error, stacktrace => Stacktrace})
```

2021-12-23 00:52 UTC, HJianBo approved these changes

2021-12-23 01:13 UTC, zmstone approved these changes

2021-12-23 14:21 UTC, merged