Improve error log
emqx/emqx pull request #6708
Opened 2022-01-12 02:25 UTC by zhongwencool

1. Add more detail log when authn/authz query error(locate the problem faster).
2. Don't log error when authn_redis query result is empty.
3. Always debug when tracing.

2022-01-12 10:26 UTC, HJianBo submitted a review, later dismissed

2022-01-13 20:57 UTC, zmstone requested changes

2022-01-13 20:57 UTC, zmstone commented on apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
> +format_meta_(Meta, Encode) ->
nit: is elvis OK with this ?

maybe `do_format_meta`

2022-01-13 20:57 UTC, zmstone commented on apps/emqx_authn/src/simple_authn/emqx_authn_jwt.erl
>          _:_Reason:_Stacktrace ->
nit: delete the `_Stacktrace` part

2022-01-13 20:57 UTC, zmstone commented on apps/emqx/include/logger.hrl
>  -define(TRACE(Event, Msg, Meta),
```suggestion
-define(TRACE(Tag, Msg, Meta),
```

2022-01-13 20:57 UTC, zmstone commented on apps/emqx/src/emqx_trace/emqx_trace_formatter.erl
> +enrich(Key, Bin) -> [Key, Bin].
```suggestion
enrich(Key, IoData) -> [Key, IoData].
```

2022-01-13 20:57 UTC, zmstone commented on apps/emqx/include/logger.hrl
>             emqx_trace:log(List, Event, Msg, Meta)
```suggestion
           emqx_trace:log(List, Msg, Meta#{trace_tag => Event})
```

2022-01-13 20:57 UTC, zmstone commented on apps/emqx/include/logger.hrl
> +        #{trace_filter => ignore})
Suggestion: add a `trace_tag` field to `Meta` for both trace and log.
trace handler should only match logs with `trace_tag` field,
but do not inverse-match `trace_filter := ignore`.


```suggestion
    ?SLOG(debug, (emqx_trace_formatter:format_meta(Meta))#{msg => Msg, trace_tag => Event}, #{})
```

2022-01-14 06:16 UTC, zmstone commented on apps/emqx/include/logger.hrl
> +        #{trace_filter => ignore})
I mean add it in this TRACE macro, but not where this macro is used.

2022-01-14 06:22 UTC, zmstone commented on apps/emqx/include/logger.hrl
> +        #{trace_filter => ignore})
Sorry, trace_tag is in use and for both trace and log

maybe a is_trace=>true for traces?

2022-01-14 07:44 UTC, zmstone approved these changes

2022-01-14 08:32 UTC, merged