(docs): fix typos
emqx/emqx pull request #6882
Opened 2022-01-27 00:44 UTC by kianmeng

2022-01-27 02:09 UTC, HJianBo approved these changes
@kianmeng  Thanks for your detailed efforts to fix so many spelling errors.

It's ok for me

2022-01-27 05:59 UTC, zmstone commented
@kianmeng thank you so much.
Please change the commit message to:
`docs: fix typo`

2022-01-27 11:10 UTC, k32 commented on apps/emqx_rule_engine/test/emqx_rule_engine_SUITE.erl
> +          "in case s.cmd != 1 "
This doesn't look like a valid change

2022-01-27 11:12 UTC, k32 requested changes
Thanks for the PR. Please revert changes in the SQL queries.

2022-01-27 11:25 UTC, zmstone commented on apps/emqx_gateway/src/coap/emqx_coap_tm.erl
> +          transport => emqx_coap_transport:transport()}.
@HJianBo I wonder why this was not found by dialyzer

2022-01-27 11:30 UTC, zmstone commented
I did a force push to @kianmeng's fork.

2022-01-27 11:38 UTC, terry-xiaoyu approved these changes

2022-01-27 12:12 UTC, k32 approved these changes

2022-01-27 12:25 UTC, merged

2022-01-28 01:20 UTC, kianmeng commented
:tada: :tada: :tada: :tada: :tada: