feature(license): check license before node start
emqx/emqx pull request #6975
Opened 2022-02-10 12:55 UTC by savonarola

2022-02-10 13:03 UTC, thalesmg commented on rebar.config.erl
> +    , {is_enterprise, "yes"}
Just a reminder that we'll also need this variable set in `mix.exs`

2022-02-10 16:21 UTC, thalesmg approved these changes

2022-02-10 17:13 UTC, zmstone commented on bin/nodetool
> +        {ok, _} -> ok;
Should check license validity too?

2022-02-10 22:08 UTC, zmstone commented on bin/nodetool
> +        {ok, _} -> ok;
Ok. Please add this as a comment.

2022-02-11 02:41 UTC, zhongwencool approved these changes

2022-02-11 05:47 UTC, zmstone requested changes
Add comments to clarify at which level of validity check is done.

2022-02-14 12:02 UTC, merged