fix authz cluster update config
emqx/emqx pull request #7360
Opened 2022-03-21 19:21 UTC by JimMoen

The acl file and cert file should be writen after EMQX sync config to all nodes.
Rather than at the node that received the API request.
Otherwise other nodes will get an empty path with no specific content.

2022-03-21 19:48 UTC, zmstone commented on apps/emqx_authz/src/emqx_authz.erl
> +        _ : _ ->
This doesn’t catch error returns from file:read_file.
Use “case of” instead of “try of”

2022-03-23 02:40 UTC, HJianBo requested changes

2022-03-23 02:40 UTC, HJianBo commented on apps/emqx_authz/src/emqx_authz_api_sources.erl
> +    update_config(Cmd, maps:without([<<"path">>], Body)).
nit: If our swagger schema doesn't support the `path` parameter, then we don't need to specifically state that it's not supported here? Just ignore it?

2022-03-23 02:40 UTC, HJianBo commented on apps/emqx_authz/src/emqx_authz.erl
> +    Path = maps:get(<<"path">>, Source, acl_conf_file()),
nit: We don't need to accept the `path` parameter?

2022-03-23 02:40 UTC, HJianBo commented on apps/emqx_authz/src/emqx_authz.erl
> +    Path = maps:get(<<"path">>, Source, acl_conf_file()),
After writing the  ACL file, do we need to check the content is syntax safe?

2022-03-24 01:21 UTC, HJianBo approved these changes

2022-03-24 01:21 UTC, merged