fix(rule): connection test when creating a resource
emqx/emqx pull request #7392
Opened 2022-03-24 02:40 UTC by DDDHuang

2022-03-24 03:40 UTC, DDDHuang commented
merge this after 4.3.13 released

2022-03-28 02:03 UTC, terry-xiaoyu requested changes

2022-03-29 08:52 UTC, terry-xiaoyu submitted a review, later dismissed

2022-03-29 09:42 UTC, DDDHuang commented
maybe something wrong in `./scripts/update-appup.sh emqx --check`

2022-03-29 11:09 UTC, terry-xiaoyu approved these changes

2022-03-29 11:09 UTC, merged

2022-03-29 11:09 UTC, JimMoen approved these changes