feat(rule_engine): default timeout for jq/2 and jq/3 with timeout
emqx/emqx pull request #7975
Opened 2022-05-17 10:03 UTC by kjellwinblad

This PR adds a default timeout of 10 seconds to the rule engine's `jq/2` function, and adds a new function `jq/3` (where the last parameter is a timeout value). The default timeout can be configured with the setting "`rule_engine.jq_function_default_timeout`".

Having a timeout when executing jq code in the rule engine is important as jq code can potentially run forever. Also, the Erlang jq library limits the number of jq programs that can execute concurrently so a jq program that loops forever could potentially also prevent a "non-buggy" jq program from ever starting.

I'm not sure that `rule_engine.jq_function_default_timeout` is the right place for the setting so please let me know if there is a better place. Also, I would like help to translate the documentation strings to Chinese.

2022-05-17 18:05 UTC, zmstone requested changes

2022-05-18 05:25 UTC, kjellwinblad commented on apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
> +    end.
Thanks, fixed [402ab7e](https://github.com/emqx/emqx/pull/7975/commits/402ab7e759f89956116a9a0e713879c75a7bdcc2)

2022-05-18 05:25 UTC, kjellwinblad commented on apps/emqx_rule_engine/src/emqx_rule_engine_schema.erl
> +-typerefl_from_string({duration_ms/0, emqx_schema, to_duration_ms}).
Thanks, fixed [402ab7e](https://github.com/emqx/emqx/pull/7975/commits/402ab7e759f89956116a9a0e713879c75a7bdcc2)

2022-05-18 05:35 UTC, zmstone commented on apps/emqx_rule_engine/i18n/emqx_rule_engine_schema.conf
> +          en: "Default timeout for the jq/2 rule engine function"
```suggestion
          en: "Default timeout for the `jq` rule engine function"
```

2022-05-18 05:35 UTC, zmstone commented on apps/emqx_rule_engine/i18n/emqx_rule_engine_schema.conf
> +          zh: "Default timeout for the jq/2 rule engine function"
```suggestion
          zh: “规则引擎内建函数 `jq` 默认时间限制”
```

2022-05-18 05:35 UTC, zmstone commented on apps/emqx_rule_engine/i18n/emqx_rule_engine_schema.conf
> +          zh: "Rule engine jq function default timeout"
```suggestion
          zh: "规则引擎 jq 函数时间限制"
```

2022-05-21 06:51 UTC, terry-xiaoyu commented
I copied this PR to https://github.com/emqx/emqx/pull/8006 and then pushed my commits to fix the CIs.

Close this one.

2022-05-21 06:51 UTC, closed without merging