fix: porting the install_upgrade.escript from v4.4
emqx/emqx pull request #8034
Opened 2022-05-24 09:08 UTC by terry-xiaoyu

2022-05-24 09:25 UTC, zmstone requested changes
5.0 do not use zip pakcages anymore.
please change (and test) the script to work with .tar.gz packages.

2022-05-24 09:25 UTC, zmstone commented on bin/install_upgrade.escript
> +            ?INFO("Cannot upgrade/downgrade to ~s from ~s~n"
```suggestion
            ?INFO("Cannot upgrade/downgrade from ~s to ~s~n"
```

2022-05-24 09:25 UTC, zmstone commented on bin/install_upgrade.escript
> +                [TargetVersion, CurrentVersion]),
```suggestion
                [CurrentVersion, TargetVersion]),
```

2022-05-24 09:25 UTC, zmstone commented on bin/install_upgrade.escript
> +                  "We only support relup between patch versions",
```suggestion
                  "Hot upgrade is only supported between patch releases.",
```

2022-05-24 09:25 UTC, zmstone commented on bin/install_upgrade.escript
> +    Scripts = [RelNameStr, RelNameStr++"_ctl", "cuttlefish", "nodetool",
```suggestion
    Scripts = [RelNameStr, RelNameStr++"_ctl", "nodetool",
```

2022-05-24 09:25 UTC, zmstone commented on bin/install_upgrade.escript
> +    {ok, _} = file:copy(CurrVmArgs, filename:join(["releases", Vsn, "vm.args"])),
this file is never used, no need to backup ?

if we do need it after all, we need to add vm_args back to boot script.

2022-05-24 09:25 UTC, zmstone commented on bin/install_upgrade.escript
> +        ZipFiles = filelib:wildcard(filename:join(["releases", RelNameStr ++ "-*" ++ Version ++ "*.zip"])),
5.0 do not use .zip file for release, tar.gz is enough.

2022-05-24 09:25 UTC, zmstone commented on bin/install_upgrade.escript
> +                  ok = erl_tar:create(GzFile, filelib:wildcard("*"), [compressed])
this will not work for tar.gz

2022-05-25 03:24 UTC, terry-xiaoyu commented on build
> +        tar -C "$rel_dir" -zxf "$tgzfile" --keep-old-files releases lib
I changed the implementation to creating tmp dirs, as the --skip-old-files option of `tar` command is not supported on Mac OSX.

2022-05-25 07:40 UTC, zmstone approved these changes

2022-05-25 07:46 UTC, merged