Refine listeners name
emqx/emqx pull request #8447
Opened 2022-07-08 02:39 UTC by JimMoen

use $type:$proto

2022-07-08 03:24 UTC, JimMoen commented
see https://github.com/emqx/minirest/pull/98

2022-07-08 05:26 UTC, zmstone commented on apps/emqx_management/src/emqx_mgmt_cli.erl
> +listeners(["restart", "management:http"]) ->
keep backward compatibility

2022-07-08 05:26 UTC, zmstone requested changes
for all API and CLI interfaces, we need to keep backward compatibility

2022-07-08 05:27 UTC, zmstone commented
Test ipv6 interface

2022-08-17 08:35 UTC, JimMoen commented
listener rename will cause client reconnect.
The impact is too big, close this PR.

2022-08-17 08:35 UTC, closed without merging