fix: cluster/local-override.conf does not take effect at vm.args/app.config
emqx/emqx pull request #8895
Opened 2022-09-05 14:54 UTC by zhongwencool

2022-09-05 15:25 UTC, zmstone requested changes
fix emqx.cmd for windows too.
also: test space in data dir.

2022-09-06 06:49 UTC, zhongwencool commented
> fix emqx.cmd for windows too. also: test space in data dir.

`/data1/test   good/` is ok.

I'm not familiar with cmd on windows, 
I don't have a windows environment to debug, 
maybe find someone to help this out.

2022-09-15 09:29 UTC, zmstone commented
will fix windows in another PR.

2022-09-15 09:30 UTC, zmstone commented on CHANGES-5.0.md
> +* Fix `cluster/local-override.conf` does not take effect at vm.args/app.config. [#8895](https://github.com/emqx/emqx/pull/8895)
5.0.8 is being released in release-5.0.8 branch.
please move this to 5.0.9

2022-12-27 12:37 UTC, zmstone commented
as discussed.
we will need to fix it in a different approach.
the hocon_cli is not quite helpful in this case.
we'll need to perform config generation just like how emqx_config:init_load does:

1. load `emqx.conf` + merge envs, to read data dir (so we know where the `{cluster|loca}-override.conf` files are, and also know to generate the `app.<time>.config` file)
2. apply`cluster-overrides.conf` + `local-overrides.conf` on top of the base
3. generate app.<time>.config

2023-01-14 06:33 UTC, closed without merging