fix(slow_subs): Fix the unit error of the `deliver_begin_at` timestamp
emqx/emqx pull request #8981
Opened 2022-09-16 08:09 UTC by lafirest

This will cause the `internal` stat type to never working and the `response` type time span error

2022-09-16 10:11 UTC, zmstone requested changes
- [] Add description
- [x] Add appup
- [x] Update CHANGES
- [x] App version bump
- [x] Test case should verify interval as expected (at least around the expected interval).

2022-09-23 06:57 UTC, HJianBo submitted a review, later dismissed
LGTM;  Could you plz check it again? @zmstone @xiangfangyang-tech

2022-09-23 06:59 UTC, ieQu1 approved these changes

2022-09-26 09:21 UTC, xiangfangyang-tech submitted a review, later dismissed

2022-09-26 10:05 UTC, merged