fix(acl): Check the real topic in delayed messages
emqx/emqx pull request #9290
Opened 2022-11-03 06:29 UTC by lafirest

We need to check the true topic of the delayed message correctly, the cheapest way to do this is to extract the true topic from the raw topic when doing ACL check

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/` dir
~~- [ ] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)~~
- [ ] For internal contributor: there is a jira ticket to track this change, and another jira tickt to track doc updates (if any)
       EMQX-7963
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## Backward Compatibility

## More information

2022-11-03 10:27 UTC, ieQu1 commented on apps/emqx/src/emqx_access_control.erl
> +            ?SLOG(error, #{
Perhaps this shouldn't be an error, since this data comes from the client? info?

2022-11-03 10:27 UTC, ieQu1 submitted a review, later dismissed

2022-11-03 10:28 UTC, zmstone requested changes

2022-11-03 10:28 UTC, zmstone commented on changes/v5.0.10-en.md
> +  Now will determine the actual topic of the delayed messages, e.g. `$delayed/1/t/foo` will be treated as  `t/foo` in authorize check
```suggestion
  Now will determine the actual topic of the delayed messages, e.g. `$delayed/1/t/foo` will be treated as  `t/foo` in authorize checks.
```

2022-11-03 10:28 UTC, zmstone commented on apps/emqx/test/emqx_access_control_SUITE.erl
> +    meck:unload(emqx_access_control),
move meck unload to end_per_testcase

2022-11-03 10:28 UTC, zmstone commented on apps/emqx/src/emqx_access_control.erl
> +            ?SLOG(error, #{
should be warning level ?

2022-11-04 13:57 UTC, qzhuyan commented on apps/emqx/src/emqx_access_control.erl
> +-compile(export_all).
nit, export the funs that is needed.

2022-11-07 09:33 UTC, zmstone approved these changes

2022-11-07 09:33 UTC, merged