fix: create trace sometime failed by end_at time has already passed
emqx/emqx pull request #9303
Opened 2022-11-04 07:56 UTC by zhongwencool

Port: https://github.com/emqx/emqx/pull/9156 

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [x] Added tests for the changes
- [x] Changed lines covered in coverage report
- [x] Change log has been added to `changes/` dir
- [x] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## Backward Compatibility

## More information

2022-11-09 12:09 UTC, zmstone commented on changes/v5.0.10-en.md
> +- Fix create trace sometime failed by end_at time has already passed. [#9302](https://github.com/emqx/emqx/pull/9302)
this has missed the 5.0.10 train, please add it to 5.0.11

2022-11-21 07:59 UTC, HJianBo requested changes

2022-11-21 07:59 UTC, HJianBo commented on changes/v5.0.11-zh.md
> +- 修复创建追踪日志时偶尔会报`end_at time has already passed`错误，导致创建失败。[#9302](https://github.com/emqx/emqx/pull/9302)
```suggestion
- 修复创建追踪日志时偶尔会报`end_at time has already passed`错误，导致创建失败。[#9303](https://github.com/emqx/emqx/pull/9303)
```

2022-11-21 07:59 UTC, HJianBo commented on changes/v5.0.11-en.md
> +- Fix create trace sometime failed by end_at time has already passed. [#9302](https://github.com/emqx/emqx/pull/9302)
```suggestion
- Fix create trace sometime failed by end_at time has already passed. [#9303](https://github.com/emqx/emqx/pull/9303)
```

2022-11-21 09:18 UTC, HJianBo approved these changes

2022-11-21 09:20 UTC, merged