feat: rule_engine_validator integer and num range support
emqx/emqx pull request #9342
Opened 2022-11-10 10:06 UTC by JimMoen

## PR Checklist
Please convert it to a draft if any of the following conditions are not met. Reviewers may skip over until all the items are checked:

- [ ] Added tests for the changes
- [ ] Changed lines covered in coverage report
- [ ] Change log has been added to `changes/` dir
- [ ] For EMQX 4.x: `appup` files updated (execute `scripts/update-appup.sh emqx`)
- [ ] For internal contributor: there is a jira ticket to track this change
- [ ] If there should be document changes, a PR to emqx-docs.git is sent, or a jira ticket is created to follow up
- [ ] In case of non-backward compatible changes, reviewer should check this item as a write-off, and add details in **Backward Compatibility** section

## Backward Compatibility

## More information
We need to add a `range` attribute to other number types, or fields that should be of type integer.

2022-11-15 02:34 UTC, terry-xiaoyu submitted a review, later dismissed

2022-11-15 02:34 UTC, terry-xiaoyu commented on apps/emqx_rule_engine/src/emqx_rule_validator.erl
> +    throw({invalid_range_interval, {max, {Val, Interval}}}).
invalid_range_interval -> invalid_range

2022-11-16 09:54 UTC, zmstone commented
this breaks compatibility ?
what happens to the users using mixed numbers ?

2022-11-16 09:55 UTC, zmstone requested changes
link jira or provide more information about why the change.

questions:
does this break compatibility ?
what happens to uses who are already using integer and float in a mixed way?

2022-11-18 02:08 UTC, closed without merging