docs: add missing changelogs for 9939
emqx/emqx pull request #9999
Opened 2023-02-20 08:11 UTC by zmstone

2023-02-20 08:28 UTC, ieQu1 approved these changes

2023-02-20 08:30 UTC, ieQu1 commented on changes/ce/fix-9939.en.md
> +Prior to this change, EMQX 'replicant' role nodes can only join cluster using 'static' cluster discovery.
```suggestion
Prior to this change, EMQX 'replicant' could not use manual discovery strategy.
```

The replicants could use other strategies as well, not just static.

2023-02-20 08:31 UTC, ieQu1 requested changes
Please see comment

2023-02-20 13:32 UTC, zmstone commented
> Please see comment

Thanks. Fixed.

2023-02-20 20:12 UTC, ieQu1 approved these changes

2023-02-23 14:01 UTC, ieQu1 approved these changes

2023-02-23 15:02 UTC, merged